danliris/com.danliris.service.core

- Com.DanLiris.Service.Core.Lib/Models/Comodity.cs
- Com.DanLiris.Service.Core.Lib/Models/MaterialConstruction.cs
- Com.DanLiris.Service.Core.Lib/Models/YarnMaterial.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/ComodityViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/MaterialConstructionViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/QualityViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/YarnMaterialViewModel.cs
> add validation

- Com.DanLiris.Service.Core.Lib/Services/ProductService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/ProductViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/Product/ProductTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/ProductsController.cs
Change Product Controller also Return Color Name and Design Code and Number
> Change Product Controller also Return Color Name and Design Code and Number

- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20181005094641_AddProductSPPProperties.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20181005094641_AddProductSPPProperties.cs
- Com.DanLiris.Service.Core.Lib/Models/Product.cs
- Com.DanLiris.Service.Core.Lib/Models/ProductSPPProperty.cs
- Com.DanLiris.Service.Core.Lib/Services/ProductService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/ProductViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/Product/ProductTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/ProductServiceDataUtil.cs
- Com.DanLiris.Service.Core.Test/Helpers/BasicServiceTest.cs
- Com.DanLiris.Service.Core.Test/Services/Product/ProductBasicTest.cs
Add Product SPP Property In Products
> Add Product SPP Property In Products

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentShippingStaffProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200606043823_Create-Garment-Shipping-Staff.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200606043823_Create-Garment-Shipping-Staff.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentShippingStaffModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentShippingStaff/GarmentShippingStaffService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentShippingStaff/IGarmentShippingStaffService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentShippingStaffViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentShippingStaff/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentShippingStaffDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentShippingStaff/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentShippingStaffController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Table Garment Shipping Staff
> Create Table Garment Shipping Staff

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentFabricTypeProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200608045336_Create-Table-Garment-Fabric-Type.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200608045336_Create-Table-Garment-Fabric-Type.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentFabricTypeModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentFabricType/GarmentFabricTypeService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentFabricType/IGarmentFabricTypeService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentFabricTypeViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentFabricType/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentFabrictTypeDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentFabricType/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentFabricTypeController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Table Garment Fabric Type - Apps DMS Shipping
> Create Table Garment Fabric Type

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentEMKLProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200608092129_Create-Table-Garment-EMKL.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200608092129_Create-Table-Garment-EMKL.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentEMKLModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentEMKL/GarmentEMKLService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentEMKL/IGarmentEMKLService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentEMKLViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentEMKL/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentLEMKLDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentEMKL/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentEMKLController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Table Garment EMKL & Trucking
> Create Table Garment EMKL & Trucking

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentForwarderProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200609084028_Create-Table-Garment-Forwarder.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200609084028_Create-Table-Garment-Forwarder.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentForwarderModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentForwarder/GarmentForwarderService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentForwarder/IGarmentForwarderService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentForwarderViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentForwarder/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentForwarderDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentForwarder/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentForwarderController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Table Garment Forwarder
> Create Table Garment Forwarder

- Com.DanLiris.Service.Core.Lib/Migrations/20200611031942_Alter-Table-Garment-LefOver-Warehouse-Buyer-110620.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200611031942_Alter-Table-Garment-LefOver-Warehouse-Buyer-110620.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentLeftoverWarehouseBuyerModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentLeftoverWarehouseBuyer/GarmentLeftoverWarehouseBuyerService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentLeftoverWarehouseBuyerViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentLeftoverWarehouseBuyerDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentLeftoverWarehouseBuyer/BasicTest.cs
Alter Table Garment LetOver WareHouse Buyer
> Alter Table Garment LetOver WareHouse Buyer

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentTransactionTypeProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200613015858_Create-Table-Transaction-Type.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200613015858_Create-Table-Transaction-Type.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentTransactionTypeModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentTransactionType/GarmentTransactionTypeService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentTransactionType/IGarmentTransactionTypeService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentTransactionTypeViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentTransactionType/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmenTransactionTypeDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentTransactionType/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentTransactionTypeController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Add Service & Create Tabel Transaction Type
> Add Service & Create Tabel Transaction Type

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentLeftoverWarehouseProductProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200615063826_Create-Table-Garment-LeftOver-WareHouse-Product.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200615063826_Create-Table-Garment-LeftOver-WareHouse-Product.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentLeftoverWarehouseProductModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentLeftoverWarehouseProduct/GarmentLeftoverWarehouseProductService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentLeftoverWarehouseProduct/IGarmentLeftoverWarehouseProductService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentLeftoverWarehouseProductViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentLeftoverWarehouseProduct/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentLeftoverWarehouseProductDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentLeftoverWarehouseProduct/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentLeftoverWarehouseProductController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Table Garment LeftOver WareHouse Product
> Create Table Garment LeftOver WareHouse Product

- Com.DanLiris.Service.Core.Lib/Migrations/20200723085837_Alter-Garment-Categories-Table.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200723085837_Alter-Garment-Categories-Table.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentCategory.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentCategoryService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentCategoryViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentCategoryControllerTests/Basic.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentCategoryDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentCategoryTests/BasicTest.cs
> Update Garment Categories

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentCourierProfile.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200910025242_Create-Table-Garment-Courier.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200910025242_Create-Table-Garment-Courier.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentCourierModel.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentEMKLModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentCourier/GarmentCourierService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentCourier/IGarmentCourierService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentEMKL/GarmentEMKLService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentCourierViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentEMKLViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentCourier/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentCourierDataUtil.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentForwarderDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentCourier/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentCourierController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Enhancement - EMKL & Forwarder
Create - Courier
> Enhancement & Create Table Garment Shipping

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentInsuranceProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200915072727_Create-Garment-Insurance-and-Courier.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20200915072727_Create-Garment-Insurance-and-Courier.cs
- Com.DanLiris.Service.Core.Lib/Migrations/CoreDbContextModelSnapshot.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentInsuranceModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentInsurance/GarmentInsuranceService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentInsurance/IGarmentInsuranceService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentInsuranceViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentInsurance/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentInsuranceDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentInsurance/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentInsuranceController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Garment Shipping - Insurance
> Create Garment Shipping - Insurance

- Com.DanLiris.Service.Core.Lib/Migrations/20201001021956_Alter-Table-Garmentt-Left-Over-Buyer.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201001021956_Alter-Table-Garmentt-Left-Over-Buyer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201005020610_Alter-Table-Garment-Insurance.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201005020610_Alter-Table-Garment-Insurance.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentInsuranceModel.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentLeftoverWarehouseBuyerModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentInsurance/GarmentInsuranceService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentLeftoverWarehouseBuyer/GarmentLeftoverWarehouseBuyerService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentInsuranceViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentLeftoverWarehouseBuyerViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentInsuranceDataUtil.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentLeftoverWarehouseBuyerDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentLeftoverWarehouseBuyer/BasicTest.cs
> Enhancement Garment Left Over Warehouse Buyer

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentAdditionalChargesProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201116035850_Create-Table-Garment-Additional-Charges.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201116035850_Create-Table-Garment-Additional-Charges.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentAdditionalChargesModel.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentLeftoverWarehouseBuyerModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentAdditionalCharges/GarmentAdditionalChargesService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentAdditionalCharges/IGarmentAdditionalChargesService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentAdditionalChargesViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentLeftoverWarehouseBuyerViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentAdditionalCharges/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentAdditionalChargesDataUtil.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentLeftoverWarehouseBuyerDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentAdditionalCharges/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentAdditionalChargesController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
- Create Table Additional Charges
- Enhancekment Garment Left Over WareHouse Buyer
> Create Table Additional Charges

- Com.DanLiris.Service.Core.Lib/Migrations/20201211022849_Alter-Table-Garment-Transaction-Type.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20201211022849_Alter-Table-Garment-Transaction-Type.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentTransactionTypeModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentTransactionType/GarmentTransactionTypeService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentTransactionTypeViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmenTransactionTypeDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentTransactionType/BasicTest.cs
> Enhancement Garment Transaction Type

- Com.DanLiris.Service.Core.Lib/Services/IBCurrency/IBCurrencyService.cs
- Com.DanLiris.Service.Core.Lib/Services/IBCurrency/IIBCurrencyService.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/BICurrencyController.cs
> Enhancement IBCurrencyRead

- Com.DanLiris.Service.Core.Lib/Models/GarmentDetailCurrency.cs
Update Validation Garment Detail Currency
> Update Validation Garment Detail Currency

- Com.DanLiris.Service.Core.Lib/Services/GarmentCategoryService.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentCategoryControllerTests/Basic.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentCategoryDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentCategoryTests/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentCategoryController.cs
> Enhance G-Category - PRD

- Com.DanLiris.Service.Core.Lib/Models/GarmentSupplier.cs
> Enhance G Supplier

- Com.DanLiris.Service.Core.Lib/Migrations/20220517020858_Add-Column-SizeIdx.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220517020858_Add-Column-SizeIdx.cs
- Com.DanLiris.Service.Core.Lib/Models/SizeModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SizeViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/SizeDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/SizeTests/SizeBasicTest.cs
> Enhance - Size

- Com.DanLiris.Service.Core.Lib/Services/GarmentDetailCurrencyService.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentDetailCurrency/BasicTests.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentDetailCurrency/GarmentDetailCurrencyBasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentDetailCurrenciesController.cs
Create Service & Controller For Omzet
> Enhance - Garment Detail Currency

- Com.DanLiris.Service.Core.Lib/Services/GarmentDetailCurrencyService.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentDetailCurrenciesController.cs
Enhance - Service & Controller | Garment Detail Currency For Omzet
> Enhance - Service & Controller

- Com.DanLiris.Service.Core.Lib/Services/GarmentDetailCurrencyService.cs
> Enhance - Service Detail Currency - PRD

- Com.DanLiris.Service.Core.Lib/Migrations/20220727024836_Add-Column-ApprovalCC-RO-On-Garment-Section.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220727024836_Add-Column-ApprovalCC-RO-On-Garment-Section.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentSection.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentSectionService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentSectionViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentSectonControllerTests/GarmentSectionControllerTest.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentSection/GarmentSectionBasicTest.cs
Add Approval PR Master / Cost Calculation
Add Approval RO Garment
> Enhance - Garment Section

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentWareHouseProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220915024713_Create-Table-Garment-Ware-Houses.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220915024713_Create-Table-Garment-Ware-Houses.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentWareHouseModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentWareHouse/GarmentWareHouseService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentWareHouse/IGarmentWareHouseService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentWareHouseViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentWareHouse/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentWareHouseDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentWareHouse/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentWareHouseController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Garment Ware House
Model, ViewModel, Service & Controller
> Create Garment Ware House - Dev

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentWareHouseProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220915024713_Create-Table-Garment-Ware-Houses.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20220915024713_Create-Table-Garment-Ware-Houses.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentWareHouseModel.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentWareHouse/GarmentWareHouseService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentWareHouse/IGarmentWareHouseService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentWareHouseViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentWareHouse/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentWareHouseDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentWareHouse/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentWareHouseController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Garment Ware House
Model, ViewModel, Service & Controller
> Create Garment Ware House

- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentProductController.cs
add getProductbyCodes fromBody
> add-ControllerGarmentProduct

- Com.DanLiris.Service.Core.Lib/AutoMapperProfiles/GarmentMarketingProfile.cs
- Com.DanLiris.Service.Core.Lib/CoreDbContext.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20221213062144_Create-Table-Garment-Marketing.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20221213062144_Create-Table-Garment-Marketing.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentMarketing.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentMarketing/GarmentMarketingService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentMarketing/IGarmentMarketingService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentMarketingViewModel.cs
- Com.DanLiris.Service.Core.Test/Controllers/GarmentMarketing/BasicTest.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentMarkeketingDataUtil.cs
- Com.DanLiris.Service.Core.Test/Services/GarmentMarketing/BasicTest.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentMarketingController.cs
- Com.DanLiris.Service.Core.WebApi/Startup.cs
Create Garment Marketing For CCG
> Create Garment Marketing

- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentSupplier.cs
- Com.DanLiris.Service.Core.Lib/Models/Supplier.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentSupplierService.cs
- Com.DanLiris.Service.Core.Lib/Services/SupplierService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentSupplierViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SupplierViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentSupplierDataUtil.cs
Add Column Country in Supplier & GarmentSupplier Table
> enhance-supplier-table | PRD

- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentSupplier.cs
- Com.DanLiris.Service.Core.Lib/Models/Supplier.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentSupplierService.cs
- Com.DanLiris.Service.Core.Lib/Services/SupplierService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentSupplierViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SupplierViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentSupplierDataUtil.cs
Add Column Country in Supplier & GarmentSupplier Table
> enhance-supplier-table - UAT

- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20240712060031_Alter_Table_Suppliers_Add_Column_Country.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentSupplier.cs
- Com.DanLiris.Service.Core.Lib/Models/Supplier.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentSupplierService.cs
- Com.DanLiris.Service.Core.Lib/Services/SupplierService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentSupplierViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SupplierViewModel.cs
- Com.DanLiris.Service.Core.Test/DataUtils/GarmentSupplierDataUtil.cs
Add Column Country in Supplier & GarmentSupplier Table
> enhance-supplier-table - DEV

- Com.DanLiris.Service.Core.Lib/Services/GarmentBuyerBrandService.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentBuyerService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentBuyerBrandViewModel.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/GarmentBuyerViewModel.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentBuyerBrandController.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentBuyersController.cs
> 2024/#18/Enhance-Garment-Buyer-Brand - DEV

- Com.DanLiris.Service.Core.Lib/Migrations/20240913090245_Modify-Tabel-Supplier-Add-New-Column.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20240913090245_Modify-Tabel-Supplier-Add-New-Column.cs
- Com.DanLiris.Service.Core.Lib/Models/Supplier.cs
- Com.DanLiris.Service.Core.Lib/Services/ProductService.cs
- Com.DanLiris.Service.Core.Lib/Services/SupplierService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SupplierViewModel.cs
Add Column Jenis Bisnis & Email
Add Keterangan (Downloada data Barang)
> 2024/#20/Enhance-Supplier-Add-Column - Dev

- Com.DanLiris.Service.Core.Lib/Migrations/20240913090245_Modify-Tabel-Supplier-Add-New-Column.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20240913090245_Modify-Tabel-Supplier-Add-New-Column.cs
- Com.DanLiris.Service.Core.Lib/Models/Supplier.cs
- Com.DanLiris.Service.Core.Lib/Services/ProductService.cs
- Com.DanLiris.Service.Core.Lib/Services/SupplierService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/SupplierViewModel.cs
Add Column Jenis Bisnis & Email
Add Keterangan (Downloada data Barang)
> 2024/#20/Enhance-Supplier-Add-Column - PRD

- Com.DanLiris.Service.Core.Lib/Helpers/Excel.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20241011014952_Add-Column-Descriptoion-Table-Garment-Suppliers.Designer.cs
- Com.DanLiris.Service.Core.Lib/Migrations/20241011014952_Add-Column-Descriptoion-Table-Garment-Suppliers.cs
- Com.DanLiris.Service.Core.Lib/Models/GarmentSupplier.cs
- Com.DanLiris.Service.Core.Lib/Services/GarmentSupplierService.cs
- Com.DanLiris.Service.Core.Lib/Services/ProductService.cs
- Com.DanLiris.Service.Core.Lib/ViewModels/XLSGarmentSupplierViewModel.cs
- Com.DanLiris.Service.Core.WebApi/Controllers/v1/BasicControllers/GarmentSuppliersController.cs
Add Description
Add Download Function
> 2024/#21/Enahnce GMt Supplier - PRD
